feat: 🎸 navigate between pages with left menu
ctrlup-io/for-developers pull request #17
Opened 2022-03-04 18:33 UTC by quibaritaenperdresatrompe

2022-03-15 11:47 UTC, MawTats commented on app/components/HideAppBar.tsx
> +      <Drawer
Le composant s'apelle HideAppBar du coup je découperai la partie Menu et j'en ferai un composant à part entière où potentiellement on pourrait mettre la const routes

2022-03-15 11:54 UTC, MawTats commented on app/root.tsx
> +            <Toolbar />
Je ne comprends pas l'ajout de ce composant "Toolbar" :/

2022-03-15 12:38 UTC, MawTats commented on app/routes/index.jsx
>        <br />
Pas du tout partisante des <br />, pour moi si le design est bien fait on aura toujours les mêmes espacements au niveau des marges des titres. De fait les espacements doivent être géré par eux :)

2022-03-15 13:44 UTC, quibaritaenperdresatrompe commented on app/root.tsx
> +            <Toolbar />
Sachant que le header est "sticky" le contenu de `<main>` est en dessous du header.

Pour éviter qu'il cache une partie du contenu nous devons le décaler, vers le bas, d'au moins la taille du header qui se trouve être conditionné par le composant `<Toolbar>` utilisé en son sein.

2022-03-15 15:34 UTC, MawTats commented on app/root.tsx
> +            <Toolbar />
ce hack me parait assez étrange qd même :D 
Moi j'aurai appliqué du coup un marginTop au Container de l'outlet

2022-03-16 09:40 UTC, quibaritaenperdresatrompe commented on app/root.tsx
> +            <Toolbar />
Honnêtement c'est pas ouf, je dois faire quelque comme ça pour me séparer du "hack" :

```jsx
<Container
  component="main"
  sx={{
    marginTop: (theme) => `calc(${theme.spacing(2)} + ${theme.components.MuiToolbar.styleOverrides.root.minHeight}px)`,
    marginBottom: (theme) => theme.spacing(8),
  }}
>
```

:thinking: qu'en penses-tu @MawTats ?

2022-03-16 09:43 UTC, quibaritaenperdresatrompe commented on app/root.tsx
> +            <Toolbar />
ou bien on n'enlève la notion de dynamisme...
```jsx
<Container
  component="main"
  sx={{
    marginTop: (theme) => theme.spacing(10),
    marginBottom: (theme) => theme.spacing(8),
  }}
>
```

2022-03-16 09:47 UTC, quibaritaenperdresatrompe commented on app/root.tsx
> +            <Toolbar />
c'est poussé avec le dernier exemple cf. 64767425bd51532e1d4ca16df7c254e1239cb91b

2022-03-16 11:09 UTC, dnazirso requested changes

2022-03-16 11:09 UTC, dnazirso commented on app/routes/contact.jsx
> +        sx={{
Pas besoin de sx sur ce Box 
```
     <Box
          bgcolor={({palette})=>palette.action.disabled}
          border={0},
          mb={2},
          width="100%"
          component="iframe"
          title="Où nous trouver"
          src={`https://www.google.com/maps/embed/v1/place?key=${data.GOOGLE_MAP_API_KEY}&q=Ctrl Up, Bordeaux`}
          allowFullScreen={false}
          loading="lazy"
       />
```

2022-03-16 11:09 UTC, dnazirso commented on app/routes/contact.jsx
> +            marginBottom: (theme) => theme.spacing(2),
si un style court se répète , 2 solution :
- utilisé les abréviation , ici : `mb={2}`
- créer une feuille de style commune sur un hook avec makeStyles() :
```
const useStyles = makeStyles(({ spacing }: Theme) => ({
  commonMargin: {
    marginBottom: spacing(2),
  },
}));
```

2022-03-16 11:09 UTC, dnazirso commented on app/routes/index.jsx
>          sx={{
pas besoin de sx, propriété reportable directement sur le Box

2022-03-16 11:09 UTC, dnazirso commented on app/routes/contact.jsx
> +        <br />
Mieux vaut préférer un mui Divider stylisé ou un spacing sur l'élément présédent `<Divider sx={{...}}/>` afin d'utilisé au mieux la centralisation du theme mui

2022-03-16 14:16 UTC, quibaritaenperdresatrompe commented on app/root.tsx
> +          marginTop: (theme) => theme.spacing(2),
Pas possible sur le composants `<Container>` :v:

2022-03-16 14:19 UTC, quibaritaenperdresatrompe commented on app/routes/contact.jsx
> +        <br />
Il est dans un texte :wink:

2022-03-16 15:08 UTC, merged

2022-03-16 15:10 UTC, dnazirso reviewed
All good