feat: 🎸 desktop version of "community" page
ctrlup-io/for-developers pull request #36
Opened 2022-08-19 15:23 UTC by quibaritaenperdresatrompe

2022-08-19 15:53 UTC, dnazirso requested changes

2022-08-19 15:53 UTC, dnazirso commented on app/routes/community.jsx
> +        <Grid item lg={6} position="relative" minHeight={440}>
peut-être remplacé par :
`<Grid display={{ xs: "none", lg: "block" }} item lg={6} position="relative" minHeight={440}>....<Grid>`

2022-08-19 15:53 UTC, dnazirso commented on app/routes/community.jsx
> +            variant={isLarge ? "quilted" : "standard"}
je comprend ici pourquoi l'usage de  `const isLarge = useMediaQuery(....)` ... 🤔 je dois réfléchir ladessus

2022-08-19 15:53 UTC, dnazirso commented on app/routes/community.jsx
> +      {isLarge && <Grid item xs />}
peut-être remplacé par :
`<Grid display={{ xs: "none", lg: "block" }} item xs />`

2022-08-19 15:53 UTC, dnazirso commented on app/routes/community.jsx
> +            <Typography fontWeight={700} display="block">
`fontWeight={700}` peut être défini dans le theme `typography.fontWeightBold: 700` puis remplacé par `fontWeight="bold"` pour profité de la puissance du theming mui ✌🏽

2022-08-19 15:53 UTC, dnazirso commented on app/routes/community.jsx
> +        <Grid item xs={12} alignContent="flex-end">
J'avoue ne pas être sur si ça marche as expected dans la mesure où le `<Grid item>` lui-même n'est possiblement pas flex 🤔 , no se

2022-08-23 09:53 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +        <Grid item lg={6} position="relative" minHeight={440}>
en effet, très cool ça !

2022-08-23 09:54 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +            <Typography fontWeight={700} display="block">
yes, bien vu ! c'est définie en ce sens sur le thème cf. https://github.com/ctrlup-io/rainbow-react/blob/main/src/theme/index.js#L7

2022-08-23 09:55 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +        <Grid item xs={12} alignContent="flex-end">
reliqua, je dois le supprimer :v:

2022-08-23 10:00 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +        <Grid item lg={6} position="relative" minHeight={440}>
en fait ça ne fonctionne pas sur une `<Grid>` 
![image](https://user-images.githubusercontent.com/26886259/186130323-0cd8b2fa-f5fd-4bbd-96d2-7b4da9ac6b43.png)

2022-08-23 10:04 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +            <Typography fontWeight={700} display="block">
:white_check_mark: corrigé sur https://github.com/ctrlup-io/for-developers/pull/36/commits/5b793779cd4ae320bfc672243895f13b12e644e3

2022-08-23 10:05 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +      {isLarge && <Grid item xs />}
ça ne semble pas possible cf. https://github.com/ctrlup-io/for-developers/pull/36#discussion_r952409802

2022-08-23 11:04 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +        <Grid item lg={6} position="relative" minHeight={440}>
:white_check_mark: Au temps pour moi, c'est ok et fixé sur https://github.com/ctrlup-io/for-developers/pull/36/commits/62b2ba31c6f383e7666deea5029b8ee175d4fc40

2022-08-23 11:04 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +      {isLarge && <Grid item xs />}
:white_check_mark: fixé sur https://github.com/ctrlup-io/for-developers/pull/36/commits/62b2ba31c6f383e7666deea5029b8ee175d4fc40

2022-08-23 12:08 UTC, quibaritaenperdresatrompe commented on app/routes/community.jsx
> +            variant={isLarge ? "quilted" : "standard"}
@dnazirso tu as pu réfléchir ? :smile:

2022-08-23 12:58 UTC, merged